(function ($, Drupal) {
  Drupal.behaviors.hideAltmetricBlock = {
    attach: function (context, settings) {
      // Delay the execution to handle element generated by
      // Altmetric js.
      setTimeout(function() {
        var $altmetricEmbed = $('.altmetric-embed a[data-content]', context);
        var $altmetricBlock = $('#block-dgi-i8-base-altmetricsblock');

        // Only execute the behavior if the altmetric block exists and has not been processed yet.
        if ($altmetricBlock.length && !$altmetricBlock.data('processed')) {

          if ($altmetricEmbed.length === 0) {
            $altmetricBlock.hide();
          }

          // Mark the altmetric block as processed.
          $altmetricBlock.data('processed', true);
        }
      }, 300);
    }
  };
})(jQuery, Drupal);
